# Generated by Django 3.1.1 on 2020-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True)),
            ],
            options={
                'db_table': 'urls',
            },
        ),
        migrations.CreateModel(
            name='UrlSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('long_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='api.longurl')),
            ],
            options={
                'db_table': 'url_slugs',
            },
        ),
    ]
