# Generated by Django 3.1.1 on 2020-09-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
            ],
            options={
                'db_table': 'urls',
            },
        ),
        migrations.CreateModel(
            name='UrlSlug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='api.urlitem')),
            ],
            options={
                'db_table': 'url_slugs',
            },
        ),
    ]
