FROM python:3.8.5-alpine3.12

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
COPY requirements ./requirements/
RUN pip install --no-cache-dir -r requirements/development.txt
COPY . .
